### PR TITLE
Remove docker:servers from tsuru.conf

### PR DESCRIPTION
**Pull request by tupy**
Fix the problem reported in https://github.com/tsuru/tsuru/issues/1041

### CODE REVIEW

**Comment by jblancett** [comment]
this problem is solved by the following line:
https://github.com/jblancett/tsuru-cookbook/blob/master/recipes/server.rb#L40
If docker:segregate: false, you will still want to define docker servers in the tsuru.conf.
Because docker:segregate is false by default, you would not want to leave this option out by default.
Does that make sense?

**Comment by andrewsmedina** [comment]
By the way, I recommend to use `segregate: true` in production. The segregate provisioner has a better scheduler.

**Comment by jblancett** [comment]
@andrewsmedina I agree.  I tried to keep the default attributes in the cookbook matching tsuru's defaults though.
Basically, if you override the segregate attribute and set it to true, the cookbook will automatically remove the docker:servers entry so you won't have to worry about it.  Which I believe is what @tupy intended to solve if I'm not mistaken?

**Comment by tupy** [comment]
:+1:

**Pull request closed without merging**
